/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Carousel: typeof import('./src/components/Carousel.vue')['default']
    CopyRight: typeof import('./src/components/CopyRight.vue')['default']
    Cropper: typeof import('./src/components/Cropper.vue')['default']
    ECharts: typeof import('./src/components/ECharts.vue')['default']
    Editor: typeof import('./src/components/Editor.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElStatistic: typeof import('element-plus/es')['ElStatistic']
    ElSubmenu: typeof import('element-plus/es')['ElSubmenu']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElText: typeof import('element-plus/es')['ElText']
    ElTiptap: typeof import('element-plus/es')['ElTiptap']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    EssayEditItem: typeof import('./src/components/EssayEditItem.vue')['default']
    LoginItem: typeof import('./src/components/LoginItem.vue')['default']
    Navigate: typeof import('./src/components/Navigate.vue')['default']
    NewsCard: typeof import('./src/components/NewsCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowUserDetail: typeof import('./src/components/ShowUserDetail.vue')['default']
  }
}
